version: '3.3'
services:
  chrome:
    image: selenium/standalone-chrome:97.0
    restart: always
    ports:
      - '4444:4444'
    shm_size: '2gb'
    networks:
      - bbrixx_network
networks:
  bbrixx_network:
    external: true